### ISSUE TITLE
1.12.0 Alpine build fail Issue with mbedtls 

### ISSUE THREAD

**Issue by Gooseware** [mongrel2/mongrel2#331] opened 2019-04-17 02:58 UTC
Issue occurs in ---

src/server.c: In function 'Server_init_rng':
src/server.c:176:29: error: 'mbedtls_havege_state' undeclared (first use in this function); did you mean 'mbedtls_sha512_starts'?
         ctx = calloc(sizeof(mbedtls_havege_state), 1);
                             ^~~~~~~~~~~~~~~~~~~~
                             mbedtls_sha512_starts
src/server.c:176:29: note: each undeclared identifier is reported only once for each function it appears in
src/server.c:177:9: warning: implicit declaration of function 'mbedtls_havege_init'; did you mean 'mbedtls_aes_init'? [-Wimplicit-function-declaration]
         mbedtls_havege_init((mbedtls_havege_state *)ctx);
         ^~~~~~~~~~~~~~~~~~~
         mbedtls_aes_init
src/server.c:177:52: error: expected expression before ')' token
         mbedtls_havege_init((mbedtls_havege_state *)ctx);
                                                    ^
src/server.c:179:25: error: 'mbedtls_havege_random' undeclared (first use in this function); did you mean 'mbedtls_ctr_drbg_random'?
         srv->rng_func = mbedtls_havege_random;
                         ^~~~~~~~~~~~~~~~~~~~~
                         mbedtls_ctr_drbg_random
make: *** [<builtin>: src/server.o] Error 1

---

Trying to build this using alpine vs 3.9 with 
make
gcc
g++
zeromq
zeromq-dev
sqlite
sqlite-dev
mbedtls-dev
mbedtls-utils
openssh
git
tar
curl

# curl -L https://github.com/mongrel2/mongrel2/releases/download/v1.12.0/mongrel2-v1.12.0.tar.bz2 | tar --strip-components=1 -xj -C m2 && cd m2 && make all install

If you would like I can add a copy of the Dockerfile i am writing to build this.

Thanks

**Comment by jasom** [comment] 2019-04-17 18:59
I know exactly what the issue is; I've been meaning to make the havege dependency optional; the last time I looked at this, mbedtls had no support for getrandom(2) *and* no option for having a persistent FD open to /dev/urandom meaning that there was no OS provided CSPRNG available in a chroot.

I'll take a look at this hopefully tonight, but maybe not until the weekend.

**Comment by Gooseware** [comment] 2019-04-18 22:25
Thanks Jason...
    Will that mean that it would not be able to support ssl ? It would be good to know for the Docker Image what the limitations would be .

**Comment by jasom** [comment] 2019-04-19 21:37
@Gooseware 

It should support ssl just fine, the code there is to work around a limitation of mbedTLS that was fixed a while ago, and I haven't gotten around to removing it.

**Comment by jasom** [comment] 2019-04-20 04:18
@Gooseware I created a PR with commit 91677ce that should resolve this, but it is not merged yet.  I tested this on nixos, which also lacks HAVEGE in the packaged mbedTLS.  Let me know if that works for you as well.

**Closed** 2019-06-14 00:37 UTC
